#:schema node_modules/wrangler/config-schema.json
name = "bsky-communities"
main = "src/index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
[observability]
enabled = true

[vars] 
ALLOWED_DOMAINS = "desu.cx"

# SECRET: CF_API_TOKEN 
# CF_API_TOKEN is an API token generated on Cloudflare with the following permissions:
# - Zone: DNS: Edit 
# - Zone: Zone: Read
# - Zone: Workers Routes: Edit 

[[d1_databases]]
binding = "DB"
database_name = "bsky-communities"
database_id = ""